<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '3d61634a005b41570a3dab552e90eab4',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/hermes?serverVersion=5.7&charset=utf8_unicode_ci',
);
