<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEL2bFlq\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEL2bFlq/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerEL2bFlq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerEL2bFlq\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \ContainerEL2bFlq\srcApp_KernelProdDebugContainer([
    'container.build_hash' => 'EL2bFlq',
    'container.build_id' => 'e9f39871',
    'container.build_time' => 1582954775,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEL2bFlq');
