<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBZCgZOr\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBZCgZOr/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerBZCgZOr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerBZCgZOr\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerBZCgZOr\srcApp_KernelProdContainer([
    'container.build_hash' => 'BZCgZOr',
    'container.build_id' => 'ca94c568',
    'container.build_time' => 1582958691,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBZCgZOr');
