<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTHzSGTY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTHzSGTY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTHzSGTY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTHzSGTY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTHzSGTY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'THzSGTY',
    'container.build_id' => '431712bc',
    'container.build_time' => 1588533628,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTHzSGTY');
