<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF5e0sih\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF5e0sih/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF5e0sih.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF5e0sih\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerF5e0sih\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'F5e0sih',
    'container.build_id' => 'd5f045bf',
    'container.build_time' => 1590760851,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF5e0sih');
